---
- name: Install Git utility 
  package: name=git state=latest 

- name: Install NFS mount utility
  package:
    name: nfs-utils
    state: latest
  when: ansible_os_family == "RedHat"

- name: Install NFS mount utility
  package:
    pkg: nfs-common
    state: present
  when: ansible_os_family == "Debian"

- name: Create NFS exports folder 
  file: 
    path: /srv/docker
    owner: root
    group: root
    mode: '0755' 
    recurse: yes
    state: directory 

- name: Mount NFS share
  mount:
    fstype: nfs
    opts: "nfsvers=3,_netdev,soft,intr"
    src: "{{NFS_SERVER}}:/srv/docker"
    path: "/srv/docker"
    state: mounted

- name: Add mountpoint on fstab 
  lineinfile:
    dest: /etc/fstab 
    line: "{{NFS_SERVER}}:/srv/docker	/srv/docker	nfs	defaults,nfsvers=3,_netdev,soft,intr	0 0"    
    state: present

- name: Install Docker 
  shell: curl https://get.docker.com |sudo bash

- name: Start docker service 
  service: 
    name: docker
    state: started

- name: Check that the swarm is alive
  stat:
    path: /srv/docker/join_swarm.sh
  register: docker_swarm

- name: Join Docker swarm 
  command: "/srv/docker/join_swarm.sh"
  when: docker_swarm.stat.exists
